require("berserkermother.config.lazy")
require("berserkermother.config.remap")
-- require("berserkermother.config.gruvbox")
require("berserkermother.config.tree-sitter")
require("berserkermother.config.nvim_comment")
require("berserkermother.config.lualine")
require("berserkermother.config.alpha")
-- require("berserkermother.config.tree")
require("berserkermother.config.colorize")
require("berserkermother.config.lspconfig")

-- side number color
-- vim.api.nvim_set_hl(0, 'SignColumn', { bg = '#3E3232' })
vim.api.nvim_set_hl(0, 'LineNr', { bg = '#4E4242' })
vim.api.nvim_set_hl(0, 'LineNrBelow', { bg = '#3E3232' })
vim.api.nvim_set_hl(0, 'LineNrAbove', { bg = '#3E3232' })
