require("berserkermother.config.lazy")
require("berserkermother.config.remap")
-- require("berserkermother.config.gruvbox")
require("berserkermother.config.tree-sitter")
require("berserkermother.config.lspconfig")
require("berserkermother.config.nvim_comment")
require("berserkermother.config.lualine")
require("berserkermother.config.alpha")
require("berserkermother.config.colorize")
